'use client'
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/seSrVoP0VuQ
 */
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { ResponsiveBar } from "@nivo/bar"
import { ResponsiveLine } from "@nivo/line"

export function Component() {
  return (
    <Card key="1" className="w-full max-w-6xl p-4">
      <div className="grid gap-4 md:grid-cols-3">
        <div className="flex flex-col gap-4">
          <Card>
            <CardHeader className="flex items-center gap-4">
              <div className="flex flex-col">
                <CardTitle className="text-base">Speed</CardTitle>
                <CardDescription className="text-xs">Current speed of the vehicle</CardDescription>
              </div>
              <GaugeIcon className="w-12 h-12 ml-auto" />
            </CardHeader>
            <CardContent className="flex items-end pb-4">
              <div className="grid w-full aspect-square items-center">
                <div className="aspect-inner">
                  <BarChart className="aspect-1" />
                </div>
              </div>
              <div className="flex-1 flex flex-col items-center gap-1 ml-4 text-2xl">
                <span>120</span>
                <span className="text-sm text-gray-500 dark:text-gray-400">Max: 180</span>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex items-center gap-4">
              <div className="flex flex-col">
                <CardTitle className="text-base">Fuel</CardTitle>
                <CardDescription className="text-xs">Remaining fuel in the tank</CardDescription>
              </div>
              <FuelIcon className="w-12 h-12 ml-auto" />
            </CardHeader>
            <CardContent className="flex items-end pb-4">
              <div className="grid w-full aspect-square items-center">
                <div className="aspect-inner">
                  <FilledtimeseriesChart className="w-full aspect-[1/1]" />
                </div>
              </div>
              <div className="flex-1 flex flex-col items-center gap-1 ml-4 text-2xl">
                <span>50%</span>
              </div>
            </CardContent>
          </Card>
        </div>
        <div className="flex flex-col gap-4">
          <Card>
            <CardHeader className="flex items-center gap-4">
              <div className="flex flex-col">
                <CardTitle className="text-base">RPM</CardTitle>
                <CardDescription className="text-xs">Engine revolutions per minute</CardDescription>
              </div>
              <GaugeIcon className="w-12 h-12 ml-auto" />
            </CardHeader>
            <CardContent className="flex items-end pb-4">
              <div className="grid w-full aspect-square items-center">
                <div className="aspect-inner">
                  <FilledtimeseriesChart className="w-full aspect-[1/1]" />
                </div>
              </div>
              <div className="flex-1 flex flex-col items-center gap-1 ml-4 text-2xl">
                <span>9000</span>
                <span className="text-sm text-gray-500 dark:text-gray-400">Max: 10000</span>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex items-center gap-4">
              <div className="flex flex-col">
                <CardTitle className="text-base">Acceleration</CardTitle>
                <CardDescription className="text-xs">Real-time acceleration of the vehicle</CardDescription>
              </div>
            </CardHeader>
            <CardContent className="flex items-end pb-4">
              <div className="grid w-full aspect-square items-center">
                <div className="aspect-inner">
                  <CurvedlineChart className="w-full aspect-[2/1]" />
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
        <Card className="grid gap-4">
          <CardHeader className="flex items-center gap-4">
            <div className="flex flex-col">
              <CardTitle className="text-base">Tire Pressure</CardTitle>
              <CardDescription className="text-xs">Real-time tire pressure for each tire</CardDescription>
            </div>
            <GaugeIcon className="w-12 h-12 ml-auto" />
          </CardHeader>
          <CardContent className="flex items-center p-0">
            <BarChart className="w-full aspect-[2/1]" />
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex items-center gap-4">
            <div className="flex flex-col">
              <CardTitle className="text-base">Acceleration Tile</CardTitle>
              <CardDescription className="text-xs">Circle with a dot to represent lateral g forces</CardDescription>
            </div>
          </CardHeader>
          <CardContent className="flex items-center justify-center p-4">
            <div className="w-24 h-24 bg-gray-300 rounded-full relative">
              <div className="w-4 h-4 bg-black rounded-full absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2" />
            </div>
          </CardContent>
        </Card>
      </div>
    </Card>
  )
}


function GaugeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m12 14 4-4" />
      <path d="M3.34 19a10 10 0 1 1 17.32 0" />
    </svg>
  )
}


function BarChart(props) {
  return (
    <div {...props}>
      <ResponsiveBar
        data={[
          { name: "Jan", count: 111 },
          { name: "Feb", count: 157 },
          { name: "Mar", count: 129 },
          { name: "Apr", count: 150 },
          { name: "May", count: 119 },
          { name: "Jun", count: 72 },
        ]}
        keys={["count"]}
        indexBy="name"
        margin={{ top: 0, right: 0, bottom: 40, left: 40 }}
        padding={0.3}
        colors={["#2563eb"]}
        axisBottom={{
          tickSize: 0,
          tickPadding: 16,
        }}
        axisLeft={{
          tickSize: 0,
          tickValues: 4,
          tickPadding: 16,
        }}
        gridYValues={4}
        theme={{
          tooltip: {
            chip: {
              borderRadius: "9999px",
            },
            container: {
              fontSize: "12px",
              textTransform: "capitalize",
              borderRadius: "6px",
            },
          },
          grid: {
            line: {
              stroke: "#f3f4f6",
            },
          },
        }}
        tooltipLabel={({ id }) => `${id}`}
        enableLabel={false}
        role="application"
        ariaLabel="A bar chart showing data"
      />
    </div>
  )
}


function FuelIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="3" x2="15" y1="22" y2="22" />
      <line x1="4" x2="14" y1="9" y2="9" />
      <path d="M14 22V4a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v18" />
      <path d="M14 13h2a2 2 0 0 1 2 2v2a2 2 0 0 0 2 2h0a2 2 0 0 0 2-2V9.83a2 2 0 0 0-.59-1.42L18 5" />
    </svg>
  )
}


function FilledtimeseriesChart(props) {
  return (
    <div {...props}>
      <ResponsiveLine
        data={[
          {
            id: "Desktop",
            data: [
              { x: "Jan", y: 43 },
              { x: "Feb", y: 137 },
              { x: "Mar", y: 61 },
              { x: "Apr", y: 145 },
              { x: "May", y: 26 },
              { x: "Jun", y: 154 },
            ],
          },
          {
            id: "Mobile",
            data: [
              { x: "Jan", y: 60 },
              { x: "Feb", y: 48 },
              { x: "Mar", y: 177 },
              { x: "Apr", y: 78 },
              { x: "May", y: 96 },
              { x: "Jun", y: 204 },
            ],
          },
        ]}
        margin={{ top: 10, right: 10, bottom: 40, left: 40 }}
        xScale={{
          type: "point",
        }}
        yScale={{
          type: "linear",
          min: 0,
          max: "auto",
        }}
        axisTop={null}
        axisRight={null}
        axisBottom={{
          tickSize: 0,
          tickPadding: 16,
        }}
        axisLeft={{
          tickSize: 0,
          tickValues: 5,
          tickPadding: 16,
        }}
        colors={["#2563eb", "#e11d48"]}
        pointSize={6}
        useMesh={true}
        curve="monotoneX"
        enableArea={true}
        gridYValues={6}
        defs={[
          {
            id: "line-chart-gradient",
            type: "linearGradient",
            colors: [
              { offset: 0, color: "inherit" },
              { offset: 200, color: "inherit", opacity: 0 },
            ],
          },
        ]}
        fill={[{ match: "*", id: "line-chart-gradient" }]}
        theme={{
          tooltip: {
            chip: {
              borderRadius: "9999px",
            },
            container: {
              fontSize: "12px",
              textTransform: "capitalize",
              borderRadius: "6px",
            },
          },
          grid: {
            line: {
              stroke: "#f3f4f6",
            },
          },
        }}
        role="application"
      />
    </div>
  )
}


function CurvedlineChart(props) {
  return (
    <div {...props}>
      <ResponsiveLine
        data={[
          {
            id: "Desktop",
            data: [
              { x: "Jan", y: 43 },
              { x: "Feb", y: 137 },
              { x: "Mar", y: 61 },
              { x: "Apr", y: 145 },
              { x: "May", y: 26 },
              { x: "Jun", y: 154 },
            ],
          },
          {
            id: "Mobile",
            data: [
              { x: "Jan", y: 60 },
              { x: "Feb", y: 48 },
              { x: "Mar", y: 177 },
              { x: "Apr", y: 78 },
              { x: "May", y: 96 },
              { x: "Jun", y: 204 },
            ],
          },
        ]}
        margin={{ top: 10, right: 10, bottom: 40, left: 40 }}
        xScale={{
          type: "point",
        }}
        yScale={{
          type: "linear",
          min: 0,
          max: "auto",
        }}
        curve="monotoneX"
        axisTop={null}
        axisRight={null}
        axisBottom={{
          tickSize: 0,
          tickPadding: 16,
        }}
        axisLeft={{
          tickSize: 0,
          tickValues: 5,
          tickPadding: 16,
        }}
        colors={["#2563eb", "#e11d48"]}
        pointSize={6}
        useMesh={true}
        gridYValues={6}
        theme={{
          tooltip: {
            chip: {
              borderRadius: "9999px",
            },
            container: {
              fontSize: "12px",
              textTransform: "capitalize",
              borderRadius: "6px",
            },
          },
          grid: {
            line: {
              stroke: "#f3f4f6",
            },
          },
        }}
        role="application"
      />
    </div>
  )
}
